# Generated by Django 5.1 on 2024-08-11 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("empresarios", "0002_alter_empresas_descricao_alter_empresas_site_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Metricas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=30)),
                ("valor", models.FloatField()),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="empresarios.empresas",
                    ),
                ),
            ],
        ),
    ]
